service: inf_openshift
provider:
  name: openwhisk
  ignore_certs: true
# package:
#   include:
#     - oc
#   exclude:
#     - main.go
#     - template.yml
#     - node_modules/**
functions:
  inf_openshift:
    handler: yannickburon/inf_openshift:serverless
    runtime: docker
plugins:
  - serverless-openwhisk